### ISSUE TITLE
panic: Asset templates/gce/template.tf not found

### ISSUE THREAD

**Issue by cmoulliard** [openshift-evangelists/openshifter#17]
When the project has been build locally

```
go get github.com/cmoulliard/openshifter
cd /Users/chmoulli/MyApplications/go-wks/src/github.com/cmoulliard/openshifter
go generate
go-bindata templates
go install
```
and that we try to create a VM on GCE, this terraforma error is reported

```
/Users/chmoulli/MyApplications/go-wks/bin/openshifter
openshifter create cluster01
INFO[0000] Generating Terraform data
panic: Asset templates/gce/template.tf not found

goroutine 1 [running]:
main.RenderTemplate(0x7fff5fbfef93, 0x9, 0x0, 0xc420016fb8, 0x3, 0x133b907, 0x6, 0x133b99d, 0x6, 0x133bc32, ...)
	/Users/chmoulli/MyApplications/go-wks/src/github.com/cmoulliard/openshifter/terraform.go:35 +0x234
main.glob..func2(0x14b5500, 0xc420016f50, 0x1, 0x1)
	/Users/chmoulli/MyApplications/go-wks/src/github.com/cmoulliard/openshifter/main.go:31 +0xa3
github.com/spf13/cobra.(*Command).execute(0x14b5500, 0xc420016f00, 0x1, 0x1, 0x14b5500, 0xc420016f00)
	/Users/chmoulli/MyApplications/go-wks/src/github.com/spf13/cobra/command.go:651 +0x23a
github.com/spf13/cobra.(*Command).ExecuteC(0x14b50c0, 0xc420072be8, 0xc4200113b0, 0x0)
	/Users/chmoulli/MyApplications/go-wks/src/github.com/spf13/cobra/command.go:726 +0x339
github.com/spf13/cobra.(*Command).Execute(0x14b50c0, 0x0, 0x0)
	/Users/chmoulli/MyApplications/go-wks/src/github.com/spf13/cobra/command.go:685 +0x2b
main.main()
	/Users/chmoulli/MyApplications/go-wks/src/github.com/cmoulliard/openshifter/main.go:112 +0x31
```

**Comment by cmoulliard** [comment]
I was not compiling the project using the branch wip-mh9
