### ISSUE TITLE
If the DNS record is not around for destroy the script throws an error

### ISSUE THREAD

**Issue by thesteve0** [openshift-evangelists/openshifter#38]
INFO:libcloud.common.google:Failed to read cached auth token from file "/root/.google_libcloud_auth.673338813121-compute@developer.gserviceaccount.com": [Errno 2] No such file or directory: '/root/.google_libcloud_auth.673338813121-compute@developer.gserviceaccount.com'
INFO:root:Looking up zone
INFO:root:Looking up DNS record console.spousty.gce.pixy.io.
Traceback (most recent call last):
  File "../main.py", line 11, in <module>
    openshifter.cli.cli()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/root/openshifter/cli.py", line 82, in destroy
    driver.destroy(cluster)
  File "/root/dns/google.py", line 38, in destroy
    record = self.get_record("A", name)
  File "/root/dns/google.py", line 48, in get_record
    return self.dns.get_record(zone.id, "%s:%s" % (type, name))
  File "/usr/lib/python3.6/site-packages/libcloud/dns/drivers/google.py", line 149, in get_record
    record_id=record_id)
libcloud.dns.types.RecordDoesNotExistError: <RecordDoesNotExistError in <libcloud.dns.drivers.google.GoogleDNSDriver object at 0x7f77bc3d7518>, record_id=A:console.spousty.gce.pixy.io., value=>

**Comment by marekjelen** [comment]
Thas has been fixed already, possible you are using older version?

**Comment by marekjelen** [comment]
My mistake, found it
