### ISSUE TITLE
Sample script contains KeyError 'attendees'

### ISSUE THREAD

**Issue by galderz** [openshift-evangelists/openshifter#60]
```
INFO:Feature(Users):Generating user admin with password password and project admin
Traceback (most recent call last):
  File "../main.py", line 14, in <module>
    openshifter.cli.cli()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/openshifter/cli.py", line 47, in create
    openshifter.create()
  File "/root/openshifter/__init__.py", line 51, in create
    self.setup()
  File "/root/openshifter/__init__.py", line 43, in setup
    features.execute("setup", self.deployment, self.cluster)
  File "/root/features/__init__.py", line 51, in execute
    ft.setup()
  File "/root/features/__init__.py", line 70, in setup
    self.call(client)
  File "/root/features/users.py", line 24, in call
    for attendee in attendees['attendees']:
KeyError: 'attendees'
```

**Comment by galderz** [comment]
PR coming in a sec...

**Comment by galderz** [comment]
Actually, in my script I just removed these lines:

    - eventbrite: <event_id>
    password_type: username # Possible values: username, fixed (add password field)

I don't know if we want to keep those in the sample.yml file and make some other adjustments, or just remove them. @marekjelen ?

**Comment by marekjelen** [comment]
The sample in the `example` is supposed to be full, i.e. describe every possible option.

We should just add comment that it's optional, just for the case of eventbrite integration.

**Comment by galderz** [comment]
Right, so add a comment and comment that section of yml too?

**Comment by galderz** [comment]
@marekjelen ?

**Comment by marekjelen** [comment]
yeah, we can add some explanatory comments

**Comment by galderz** [comment]
I've sent a PR to comment the section. I can't provide explanatory comments cos I don't really know how the evenbrite stuff works.

**Comment by marekjelen** [comment]
LGTM
