### ISSUE TITLE
Error when full version specified

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift-evangelists/openshifter#66]
With latest release, if I have a version "v3.7.0-rc.0" it gives me the following error:

```
docker run -ti --rm -v /Users/jmorales/openshifter/pixy/workshops:/root/data:Z docker.io/osevg/openshifter:latest create jorge-sc
Traceback (most recent call last):
  File "../main.py", line 14, in <module>
    openshifter.cli.cli()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/openshifter/cli.py", line 46, in create
    openshifter.load(name)
  File "/root/openshifter/__init__.py", line 21, in load
    self.deployment = Deployment(name)
  File "/root/openshifter/deployment.py", line 15, in __init__
    self.version = Version(self.data['release'])
  File "/root/openshifter/deployment.py", line 82, in __init__
    self.openshift, self.major = vs
ValueError: too many values to unpack (expected 2)
```

If I specify version "v3.7" it works. This change is not backwards compatible and break all current configs.

**Comment by marekjelen** [comment]
Full version with suffix was not supported. I have some code in my working copy to support it.

V3.7 works as ocu will try to figure out what the besst patch version is and what tag to use.

**Comment by jorgemoralespou** [comment]
But 3.6.1 did work and it failed for me as well

**Comment by marekjelen** [comment]
Do you remember if the v3.6.1 was the same error?

**Comment by galderz** [comment]
With `v3.6.1` I'm getting:

```
Traceback (most recent call last):
  File "../main.py", line 14, in <module>
    openshifter.cli.cli()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/openshifter/cli.py", line 47, in create
    openshifter.create()
  File "/root/openshifter/__init__.py", line 50, in create
    self.install()
  File "/root/openshifter/__init__.py", line 35, in install
    features.execute("install", self.deployment, self.cluster)
  File "/root/features/__init__.py", line 51, in execute
    ft.setup()
  File "/root/features/ocu.py", line 21, in setup
    major, minor, rel, hash = self.execute("master", cmd).stdout.strip().split(" ")
ValueError: not enough values to unpack (expected 4, got 1)
```

**Comment by galderz** [comment]
This might be a slightly different issue and the code has moved on, I'll open a new issue.
