### ISSUE TITLE
OpenShift 3.6.1 not working

### ISSUE THREAD

**Issue by galderz** [openshift-evangelists/openshifter#69]
With v3.6.1 I'm getting:

```
Traceback (most recent call last):
  File "../main.py", line 14, in <module>
    openshifter.cli.cli()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/openshifter/cli.py", line 47, in create
    openshifter.create()
  File "/root/openshifter/__init__.py", line 50, in create
    self.install()
  File "/root/openshifter/__init__.py", line 35, in install
    features.execute("install", self.deployment, self.cluster)
  File "/root/features/__init__.py", line 51, in execute
    ft.setup()
  File "/root/features/ocu.py", line 21, in setup
    major, minor, rel, hash = self.execute("master", cmd).stdout.strip().split(" ")
ValueError: not enough values to unpack (expected 4, got 1)
```

I've also tried `v3.6` and I get the same error.

**Comment by galderz** [comment]
Btw, I'm unable to use OpenShift 3.7 due to [fabric8 maven plugin redeployment issues](https://github.com/fabric8io/fabric8-maven-plugin/issues/1130). My only workaround is to switch to binary uploads which is not ideal when having to build on Google Cloud since I have to send complete binary jars over rather than having OpenShift build it itself. @marekjelen Any chance you could check this out?

**Comment by marekjelen** [comment]
`3.6` moved out of the first releases page so the script to figure where to get the `oc` binary.

**Comment by marekjelen** [comment]
Changed the lookup script to use Github API and `jq`

**Comment by galderz** [comment]
Thanks! It's all working now :)

**Comment by marekjelen** [comment]
+1
